### List all employees

GET http://localhost:8080/api/employees
Accept: application/json

### Find employee by id

GET http://localhost:8080/api/employees/5
Accept: application/json


### Create employee

POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Jane Doe"
}

### Create employee with address

POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Jane Doe",
  "addresses": [
    {
      "city": "Budapest"
    }
  ]
}

### Update

PUT http://localhost:8080/api/employees/1
Content-Type: application/json

{
  "name": "Jack Doe"
}

### Delete

DELETE http://localhost:8080/api/employees/2

### Call Learn web services
POST https://apps.learnwebservices.com/services/hello
Content-Type: application/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <HelloRequest xmlns="http://learnwebservices.com/services/hello">
            <Name>Oktató</Name>
        </HelloRequest>
    </soapenv:Body>
</soapenv:Envelope>

### Web Service
POST http://localhost:8080/services/employees
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <findAllEmployees xmlns="https://training360.com/employees"/>
    </soap:Body>
</soap:Envelope>

